import type { Theme, ThemeColors } from './themeTypes';

/**
 * To add a theme, append an entry here. Every colour used by the UI is a
 * token in `ThemeColors`; components never reference raw theme colours.
 */
export const THEMES: Theme[] = [
  {
    id: 'typewriter',
    name: 'Typewriter',
    description: 'ivory notebook, ink ribbon',
    scheme: 'light',
    preview: ['#fffdf7', '#b5525a', '#2b2926'],
    colors: {
      background: '#f3eee4',
      surface: '#fbf8f1',
      paper: '#fffdf7',
      paperBorder: '#e6dece',
      text: '#2b2926',
      textMuted: '#6f6961',
      textFaint: '#a39b8f',
      border: '#e1d8c8',
      accent: '#b0505a',
      accentContrast: '#fffdf7',
      accentSoft: '#f4e2de',
      highlight: '#fbf0b8',
      selection: 'rgba(176, 80, 90, 0.17)',
      shadow: 'rgba(84, 64, 40, 0.16)',
      paperLine: 'rgba(120, 98, 72, 0.12)',
    },
  },
  {
    id: 'sakura',
    name: 'Sakura',
    description: 'cream & cherry blossom',
    scheme: 'light',
    preview: ['#fffaf6', '#d48896', '#7a5248'],
    colors: {
      background: '#f8efea',
      surface: '#fffaf7',
      paper: '#fffcf9',
      paperBorder: '#f0dcd5',
      text: '#3a2e2c',
      textMuted: '#80706b',
      textFaint: '#b39f99',
      border: '#ecd8d1',
      accent: '#c06676',
      accentContrast: '#fffcf9',
      accentSoft: '#f8e2e5',
      highlight: '#fde3e8',
      selection: 'rgba(192, 102, 118, 0.18)',
      shadow: 'rgba(120, 70, 70, 0.14)',
      paperLine: 'rgba(192, 102, 118, 0.13)',
    },
  },
  {
    id: 'matcha',
    name: 'Matcha',
    description: 'green tea, linen, wood',
    scheme: 'light',
    preview: ['#fbfaf1', '#7b9659', '#9b8061'],
    colors: {
      background: '#edefe2',
      surface: '#f8f8ee',
      paper: '#fcfbf3',
      paperBorder: '#dde0cb',
      text: '#2e3127',
      textMuted: '#696d5d',
      textFaint: '#a0a38f',
      border: '#d8dbc5',
      accent: '#64804a',
      accentContrast: '#fcfbf3',
      accentSoft: '#e2e9d2',
      highlight: '#e8efc9',
      selection: 'rgba(100, 128, 74, 0.18)',
      shadow: 'rgba(70, 72, 40, 0.14)',
      paperLine: 'rgba(100, 128, 74, 0.14)',
    },
  },
  {
    id: 'seoul-morning',
    name: 'Seoul Morning',
    description: 'powder blue & lavender',
    scheme: 'light',
    preview: ['#ffffff', '#8aa4d6', '#b9b3dc'],
    colors: {
      background: '#f0f3f8',
      surface: '#fbfcfe',
      paper: '#ffffff',
      paperBorder: '#e0e5ee',
      text: '#252a33',
      textMuted: '#687180',
      textFaint: '#a2a9b6',
      border: '#dde3ec',
      accent: '#5f7db3',
      accentContrast: '#ffffff',
      accentSoft: '#e4ebf7',
      highlight: '#e3ebfb',
      selection: 'rgba(95, 125, 179, 0.18)',
      shadow: 'rgba(50, 65, 100, 0.13)',
      paperLine: 'rgba(95, 125, 179, 0.13)',
    },
  },
  {
    id: 'peach-milk',
    name: 'Peach Milk',
    description: 'cream, peach, soft coral',
    scheme: 'light',
    preview: ['#fffbf6', '#f0a487', '#e6a5b0'],
    colors: {
      background: '#fbefe6',
      surface: '#fff8f2',
      paper: '#fffbf7',
      paperBorder: '#f1ddcf',
      text: '#3b2f2a',
      textMuted: '#82706a',
      textFaint: '#b8a399',
      border: '#efdacb',
      accent: '#c4664a',
      accentContrast: '#fffbf7',
      accentSoft: '#fde3d6',
      highlight: '#ffe1cd',
      selection: 'rgba(207, 111, 82, 0.17)',
      shadow: 'rgba(120, 70, 50, 0.14)',
      paperLine: 'rgba(207, 111, 82, 0.12)',
    },
  },
  {
    id: 'lavender-study',
    name: 'Lavender Study',
    description: 'quiet lilac desk',
    scheme: 'light',
    preview: ['#fefdff', '#9a88c6', '#8b8798'],
    colors: {
      background: '#f2f0f8',
      surface: '#fbfaff',
      paper: '#fefdff',
      paperBorder: '#e3dfef',
      text: '#2d2a38',
      textMuted: '#706b82',
      textFaint: '#a8a3b8',
      border: '#e0dcec',
      accent: '#7d6aad',
      accentContrast: '#fefdff',
      accentSoft: '#ebe5f7',
      highlight: '#ece3fa',
      selection: 'rgba(125, 106, 173, 0.18)',
      shadow: 'rgba(70, 60, 100, 0.14)',
      paperLine: 'rgba(125, 106, 173, 0.12)',
    },
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    description: 'late train, neon haze',
    scheme: 'dark',
    preview: ['#1b2030', '#a99cf0', '#7aa2f7'],
    colors: {
      background: '#151925',
      surface: '#1c2131',
      paper: '#1e2334',
      paperBorder: '#2b3249',
      text: '#dfe2f0',
      textMuted: '#9da3bd',
      textFaint: '#6b7290',
      border: '#2d344c',
      accent: '#ab9ef2',
      accentContrast: '#151925',
      accentSoft: 'rgba(171, 158, 242, 0.15)',
      highlight: 'rgba(122, 162, 247, 0.24)',
      selection: 'rgba(171, 158, 242, 0.28)',
      shadow: 'rgba(0, 0, 0, 0.45)',
      paperLine: 'rgba(171, 158, 242, 0.08)',
    },
  },
  {
    id: 'ar-console',
    name: 'AR Console',
    description: 'heads-up display, cyan glass',
    scheme: 'dark',
    preview: ['#08111b', '#5fd4f5', '#d7f3ff'],
    colors: {
      background: '#050a10',
      surface: '#0a131e',
      paper: '#08111b',
      paperBorder: 'rgba(95, 212, 245, 0.22)',
      text: '#d9f4ff',
      textMuted: '#86b3c8',
      textFaint: '#4f7a8f',
      border: 'rgba(95, 212, 245, 0.2)',
      accent: '#5fd4f5',
      accentContrast: '#04121a',
      accentSoft: 'rgba(95, 212, 245, 0.12)',
      highlight: 'rgba(95, 212, 245, 0.2)',
      selection: 'rgba(95, 212, 245, 0.28)',
      shadow: 'rgba(0, 0, 0, 0.6)',
      paperLine: 'rgba(95, 212, 245, 0.07)',
    },
  },
];

export const DEFAULT_THEME_ID = 'typewriter';

export function getTheme(id: string): Theme {
  return THEMES.find((t) => t.id === id) ?? THEMES[0];
}

const TOKEN_NAMES: Record<keyof ThemeColors, string> = {
  background: '--background',
  surface: '--surface',
  paper: '--paper',
  paperBorder: '--paper-border',
  text: '--text',
  textMuted: '--text-muted',
  textFaint: '--text-faint',
  border: '--border',
  accent: '--accent',
  accentContrast: '--accent-contrast',
  accentSoft: '--accent-soft',
  highlight: '--highlight',
  selection: '--selection',
  shadow: '--shadow',
  paperLine: '--paper-line',
};

/** Writes a theme's tokens onto <html> as CSS custom properties. */
export function applyTheme(theme: Theme, root: HTMLElement = document.documentElement) {
  for (const key of Object.keys(TOKEN_NAMES) as (keyof ThemeColors)[]) {
    root.style.setProperty(TOKEN_NAMES[key], theme.colors[key]);
  }
  root.dataset.theme = theme.id;
  root.dataset.scheme = theme.scheme;
  root.style.colorScheme = theme.scheme;
  document.querySelector('meta[name="theme-color"]')?.setAttribute('content', theme.colors.background);
}
